version: "3"
services:

  postgres-smartmesssage:
    container_name: postgres-totemquarkclinic
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=totemquarkclinic
    volumes:
      - postgres-totemquarkclinic-volume:/data/postgres
    ports:
      - "5532:5432"

volumes:
  postgres-totemquarkclinic-volume:

